source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "e3833e01-622c-414b-888e-46eb2eb0bf0e"
  client_secret                     = "pRn8Q~w2lwPn3gyIZ7BueCz_EO8B0uzoKVI~GcnG"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "16.04-LTS"
  location                          = "East US"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "a910367c-a6cc-48d8-759f-6c30aaab759a-test-westus"
  os_type                           = "Linux"
  subscription_id                   = "daeabc47-d5a8-4514-b01b-17305adf956a"
  tenant_id                         = "e8a64aeb-fc47-4028-996f-bd40b2c43782"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["apt-get update", "apt-get upgrade -y", "apt-get -y install nginx", "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
    inline_shebang  = "/bin/sh -x"
  }

}